### ISSUE TITLE
Need to add default Azure credential support to Akka.Persistence.Azure.Hosting

### ISSUE THREAD

**Issue by Aaronontheweb** [petabridge/Akka.Persistence.Azure#221]
https://github.com/petabridge/Akka.Persistence.Azure/pull/155 - need to add support for this for table storage and blob storage inside the new Akka.Persistence.Azure.Hosting library we're shipping.

**Comment by wesselkranenborg** [comment]
This indeed caused us some headaches after we found out that there was some mismatch between blob and table support for DefaultAzureCredential. Blob supports it, but if you use Akka.Persistence.Azure.Hosting you also need to set `.WithAzureBlobsSnapshotStore(string.Empty)` to initialize the blob storage, but connection information is set via `AzureBlobSnapshotSetup.Create`, which is not part of the `AzureBlobSnapshotStoreSettings`. This caused some confusion. But good to read that this will be unified and working the same.

My suggestion would be to create some Akka.Persistence.Azure.Hosting which support
`.WithAzureBlobsSnapshotStore(new DefaultAzureCredential())`
`.WithAzureTableJournal(new DefaultAzureCredential())`
`.WithAzurePersistence(new DefaultAzureCredential())`

**Comment by wesselkranenborg** [comment]
After some tests I know for sure that I need `.WithAzureBlobsSnapshotStore("MyStorageConnectionString")` to get Blob Snapshots work. And this Akka.Hosting feature is not working together with `AzureBlobSnapshotSetup.Create`.

So if you use Akka.Persistence.Azure.Hosting to setup `Akka.Persistence.Azure` the following combinations work:
* DefaultAzureCredentials via `AzureBlobSnapshotSetup.Create` together with HOCON configuration for BlobSnapshots
* `WithAzureBlobsSnapshotStore` with the use of a connectionstring.

These both options work together with `WithAzureTableJournal` because that one always needs a connection string.

**Comment by Arkatufus** [comment]
@wesselkranenborg All those problems should be addressed in #237

**Comment by wesselkranenborg** [comment]
Indeed, looks very good. Am eager to try it ;-)
