### ISSUE TITLE
Under high load 'The batch request operation exceeds the maximum 100 changes per change set.' exceptions are thrown when using this plugin in Akka.Cluster.Sharding

### ISSUE THREAD

**Issue by wesselkranenborg** [petabridge/Akka.Persistence.Azure#251]
When our system is under high load the following exceptions are thrown if we use Akka.Persistence.Azure as persistence for Akka.Cluster.Sharding.

Is it possible to batch this in chunks of maximum 100 items? Then we work around this limitation of Azure Tables.

Azure.Data.Tables.TableTransactionFailedException: 99:The batch request operation exceeds the maximum 100 changes per change set.
RequestId:b4783f09-5002-002e-4c1c-cf0034000000
Time:2022-09-23T07:19:30.2557589Z
 The index of the entity that caused the error can be found in FailedTransactionActionIndex.
Status: 400 (Bad Request)
ErrorCode: InvalidInput

Additional Information:
FailedEntity: 99

Content:
{"odata.error":{"code":"InvalidInput","message":{"lang":"en-US","value":"99:The batch request operation exceeds the maximum 100 changes per change set.\nRequestId:b4783f09-5002-002e-4c1c-cf0034000000\nTime:2022-09-23T07:19:30.2557589Z"}}}

Headers:
X-Content-Type-Options: REDACTED
Cache-Control: no-cache
DataServiceVersion: 3.0;
Content-Type: application/json;odata=minimalmetadata;streaming=true;charset=utf-8

   at Azure.Data.Tables.TableRestClient.SendBatchRequestAsync(HttpMessage message, CancellationToken cancellationToken)
   at Azure.Data.Tables.TableClient.SubmitTransactionInternalAsync(IEnumerable`1 transactionalBatch, Guid batchId, Guid changesetId, Boolean async, CancellationToken cancellationToken)
   at Azure.Data.Tables.TableClient.SubmitTransactionAsync(IEnumerable`1 transactionActions, CancellationToken cancellationToken)
   at Akka.Persistence.Azure.Journal.AzureTableStorageJournal.DeleteMessagesToAsync(String persistenceId, Int64 toSequenceNr)
   at Akka.Util.Internal.AtomicState.CallThrough(Func`1 task)
   at Akka.Util.Internal.AtomicState.CallThrough(Func`1 task)
   at Akka.Persistence.Journal.AsyncWriteJournal.<>c__DisplayClass18_0.<<HandleDeleteMessagesTo>g__ProcessDelete|0>d.MoveNext()

The actorpath where this is happening is: akka://\<my-actorsystem\>/system/sharding/\<my-shard-region\>/5.
These are the region stats from PBM during this time:
![image](https://user-images.githubusercontent.com/4964604/191911925-5e30c284-fa69-4f3e-a457-154ab96bba6b.png)

The formatted message in the logging is:
> [22/09/23-07:19:30.4253][akka.tcp://\<my-actorsystem\>@10.250.0.128:12552/system/sharding/heartbeat-shard/5][akka://\<my-actorsystem\>/system/sharding/\<my-shard-region\>/5][0022]: PersistentShard messages to [5000] deletion failure: [99:The batch request operation exceeds the maximum 100 changes per change set. RequestId:b4783f09-5002-002e-4c1c-cf0034000000 Time:2022-09-23T07:19:30.2557589Z The index of the entity that caused the error can be found in FailedTransactionActionIndex. Status: 400 (Bad Request) ErrorCode: InvalidInput Additional Information: FailedEntity: 99 Content: {"odata.error":{"code":"InvalidInput","message":{"lang":"en-US","value":"99:The batch request operation exceeds the maximum 100 changes per change set.\nRequestId:b4783f09-5002-002e-4c1c-cf0034000000\nTime:2022-09-23T07:19:30.2557589Z"}}} Headers: X-Content-Type-Options: REDACTED Cache-Control: no-cache DataServiceVersion: 3.0; Content-Type: application/json;odata=minimalmetadata;streaming=true;charset=utf-8 ]

**Comment by Aaronontheweb** [comment]
> Is it possible to batch this in chunks of maximum 100 items? Then we work around this limitation of Azure Tables.

I'm trying to understand what the underlying cause of this is - it's definitely not that the `PersistentShardCoordinator` is calling `PersistAll` on 100+ events at a time, since that's not how that code works in v1.4:

https://github.com/akkadotnet/akka.net/blob/231c8c9179c37c658bd7963bd0085b4f1919e87a/src/contrib/cluster/Akka.Cluster.Sharding/PersistentShardCoordinator.cs#L1478-L1482

or in v1.5:

https://github.com/akkadotnet/akka.net/blob/b0529e9df1b9c1e83ac107bd17475ed5f607e814/src/contrib/cluster/Akka.Cluster.Sharding/PersistentShardCoordinator.cs#L222-L226

So we're definitely not, at the sharding layer, batching things in groups of 100 or more.

In the journal, we do batch multiple atomic writes together - and those "batches" usually come in the form of a `PersistAll` call. So I wonder if this is something that's happening inside your application itself.

https://github.com/petabridge/Akka.Persistence.Azure/blob/7d73823c45263e5866ae8907a7f78ee6b1ab10db/src/Akka.Persistence.Azure/Journal/AzureTableStorageJournal.cs#L356

Nonetheless, we can fix this - I think the trick is to chunk each "batch" into 100 items or fewer (and remember: we have to include the `MaxSeqNo` operations as part of that 100). This can be accomplished with some basic chunking (in a `foreach` or LINQ) calls I believe.

**Comment by Arkatufus** [comment]
This is definitely something on our side, I think I might need to add more batching check after the last SDK upgrade, I'll work on this today
